Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    ## DB VM
    config.vm.define "db01" do |db01|
        db01.vm.box = "centos/stream9"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.15"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
    end

    ## Memcache VM
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "centos/stream9"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.16"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
    end

    ## RabitMQ VM
    config.vm.define "mq01" do |mq01|
        mq01.vm.box = "centos/stream9"
        mq01.vm.hostname = "mq01"
        mq01.vm.network "private_network", ip: "192.168.56.17"
        mq01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
    end

    ## Tomcat VM
    config.vm.define "app01" do |app01|
        app01.vm.box = "centos/stream9"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", ip: "192.168.56.18"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
    end

    ## Nginx VM
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.19"
        web01.vm.provider "virtualbox" do |vb|
            vb.gui = true
            vb.memory = "1024"
            vb.cpus = 1
        end
    end
end

