Vagrant.configure("2") do |config|
    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "generic/centos9s"
        vm1.vm.box_version = "4.3.12"
        vm1.vm.network "private_network", ip: "192.168.56.23"
        vm1.vm.network "public_network"
        vm1.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 2
        end
        # vm1.vm.provision "shell", run:"always", inline: <<-SHELL
        #     yum install -y httpd wget zip unzip
        #     SHELL
    end
end