Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    ##DB VM
    config.vm.define "db01" do |db01|
        db01.vm.box = 'centos/stream9'
        db01.vm.hostname = 'db01'
        db01.vm.network "private_network", ip: "192.168.56.20"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end 
        db01.vm.provision "shell", path: "provision_db.sh"
    end

    ##Memcached VM
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = 'centos/stream9'
        mc01.vm.hostname = 'mc01'
        mc01.vm.network "private_network", ip: "192.168.56.21"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
        end 
        mc01.vm.provision "shell", path: "provision_mc.sh"
    end

    ##RabbitMQ VM
    config.vm.define "mq01" do |mq01|
        mq01.vm.box = 'centos/stream9'
        mq01.vm.hostname = 'mq01'
        mq01.vm.network "private_network", ip: "192.168.56.22"
        mq01.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
        end
        mq01.vm.provision "shell", path: "provision_mq.sh"
    end

    ##App VM
    config.vm.define "app01" do |app01|
        app01.vm.box = 'centos/stream9'
        app01.vm.hostname = 'app01'
        app01.vm.network "private_network", ip: "192.168.56.23"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        app01.vm.provision "shell", path: "provision_app.sh"
    end

    ##Load Balancer VM
    config.vm.define "web01" do |web01|
        web01.vm.box = 'centos/stream9'
        web01.vm.hostname = 'web01'
        web01.vm.network "private_network", ip: "192.168.56.24"
        web01.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
        end
        web01.vm.provision "shell", path: "provision_web.sh"
    end
end